[package]
name = "netsound"
version = "0.1.0"
authors = ["MOZGIII <mike-n@narod.ru>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
mio = "0.6"
parking_lot = "0.8"
audiopus = "0.1"

[dependencies.cpal]
git = "https://github.com/MOZGIII/cpal.git"
rev = "0354548426f7b4c48392cae9876a3e77ea5c1c40"

[dependencies.libpulse-binding]
git = "https://github.com/MOZGIII/pulse-binding-rust.git"
rev = "251032e29fa5ce287a814774d29378932afc0ab0"
default-features = false
optional = true

[dependencies.libpulse-simple-binding]
git = "https://github.com/MOZGIII/pulse-binding-rust.git"
rev = "251032e29fa5ce287a814774d29378932afc0ab0"
default-features = false
optional = true

[dependencies.crossbeam-utils]
version = "0.6"
optional = true

[features]
pulse_simple_backend = ["libpulse-binding", "libpulse-simple-binding", "crossbeam-utils"]
